### ISSUE TITLE
Maps - translated labels not being used

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#107]
Environment

[https://feature.visitscotland.com/?vs_brxm_host=172.28.87.25&vs_brxm_port=8018&vs_brxm_http_host=feature.visitscotland.com&vs_ssr_http_port=8218&vs_tln_http_port=8318&vs_feature_branch=PR-1109&vs_ssr_proxy=on]

 

The following labels are not being used in maps

 

*ALL maps* 

Key: map.zoomin - translations for 'zoom in'

Key: map.zoomout - translations for 'zoom out'

 map.exitfullscreen -  translations for 'enter full screen'

Steps to Recreate
 1. Navigate to any map 
 2. in the map view, hover over the icons
 3. the zoom in, zoom out and full screen information displays in English

 *Notes*

 -We're sorry you can't zoom in any more,-  -  just Dutch label to be updated

-We're sorry you can't zoom out any more-  - just Dutch label to be updated

**Comment by KirstyScott** [comment]
Hi @MichaelGrahamVS, I've reached out to Willem and asked about translation. He's advised that he's only available for emergency translations and has asked that I feed this back to the team. 

Would this be able to wait until we have Dutch resource? 

cc. @nikkisherret @shenderson4

**Comment by nikkisherret** [comment]
Sorry @KirstyScott @MichaelGrahamVS had forgotten about this - we have Dutch resource now so I can pass this on. Thanks.

**Comment by KirstyScott** [comment]
Thanks @nikkisherret :) I've already emailed translations so they should have the request. 

That's a good question about labels, @MichaelGrahamVS do you know?

**Comment by KirstyScott** [comment]
Translations below: 

•	We're sorry, you can't zoom in any more - Helaas, je kunt niet verder inzoomen

•	We're sorry, you can't zoom out any more - Helaas, je kunt niet verder uitzoomen

**Comment by MichaelGrahamVS** [comment]
Hi @nikkisherret my understanding is that all in-language labels need updated in the CMS and we should now have all the translations. Let me know if I'm misunderstanding and we can jump on a quick call.

cc @KirstyScott

**Comment by MichaelGrahamVS** [comment]
Hi @nikkisherret, the remaining work for this ticket is as follows:

For our map with sidebar component, labels that appear on hover for 'zoom in', 'zoom out' and 'enter fullscreen' need to be updated for all languages (DE, FR, IT, ES and NL). At the moment, they are all displaying in English. 

Screenshot below as an example. Please let me know if anything is unclear. Thanks!

![screenshot-1](https://github.com/visitscotland/vs-component-library/assets/135990560/fda988d6-d207-4b02-b0a5-cbc9712856dd)

**Comment by nikkisherret** [comment]
Hey @MichaelGrahamVS have checked the CMS and the content is there - we have all the languages for zoom in and zoom out, and we don't have a label for Enter fullscreen, we have Show fullscreen and Exit fullscreen. I spoke with Juan Luis to check, and it might be a front end issue with hard-coded text, maybe one for Duncan to check? Thanks!

![image](https://github.com/visitscotland/vs-component-library/assets/146347598/872ae4a0-326a-48d1-bbf8-076e1b37895e)

**Comment by MichaelGrahamVS** [comment]
Thanks for clarifying, @nikkisherret. @duncansanderson - one to investigate in a future Sprint.
