### ISSUE TITLE
Images not appearing on Mega Nav cards when viewing in eu languages

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#117]
Images not appearing in Meganav cards when the user clicks on inspiration. 

![Image](https://user-images.githubusercontent.com/140492229/266352700-253b02fa-5322-43c4-888f-f5b3f2d2773a.png)
![Image](https://user-images.githubusercontent.com/140492229/266352701-3bd87fc9-f323-43a3-81ed-4b6081e052f6.png)

**Comment by MichaelGrahamVS** [comment]
Hi @KirstyScott can you revisit this with @nikkisherret please to determine whether there is an action here?

**Comment by KirstyScott** [comment]
Hi @MichaelGrahamVS, @nikkisherret and I had a catch-up on this. For me, they only images appearing are in German. The CMS doesn't allow the Content Team to do anything without an image, so it's not a user error. Since the issue is sporadic, this makes it hard to emulate and investigate. Due to this, the only option we can come up with for now is removing them

**Comment by MichaelGrahamVS** [comment]
Hi @nikkisherret & @KirstyScott - thanks for looking into this. Given the issue is hard to replicate I agree that the best course of action is to remove all images from the meganav for now. @nikkisherret can someone in your team action that please?

Thanks,
Michael

**Comment by nikkisherret** [comment]
@MichaelGrahamVS @KirstyScott removed in all languages. Thanks.

**Comment by MichaelGrahamVS** [comment]
Thanks @nikkisherret :-)
