### ISSUE TITLE
(Analytics) Video missing variables

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#141]
Bug: Video tracking is missing variables

See dentsu page types PDF for details of parameters/tracking required in datalayer

 https://xd.adobe.com/view/2ed199ce-5a07-46df-9692-a0a21717855d-7b82/

Currently 'site_language' is being tracked as 'language' as per other tracking requirements

This needs to be amended as per the above PDF document requirements

**Comment by duncansanderson** [comment]
I've updated the datalayer video template (VideoTrackingTemplate), changing `site_language` to `language`.

@CorinaMala you can test this change here: https://646df3398f07e38a95184dbb-tjmdkupqri.chromatic.com/?path=/story/video--default

I've added a new addon to Storybook that allows us to test the datalayer, you should see a new "datalayer watcher" tab. This will show our custom events/variables when they get added to the datalayer. You can trigger the video events by starting/pausing the video.

![2024-03-19 16_54_54-Window](https://github.com/visitscotland/vs-component-library/assets/16222436/ac6c2a72-0be9-4f95-9131-a08248a28ef6)

**Comment by CorinaMala** [comment]
@duncansanderson the change from site_language to language is correctly appearing on storybook, and the video is working as expected on the different devices. **Ready to be merged to develop**
