### ISSUE TITLE
(FED) PSW - Incorrect colour contrast in Select input

### ISSUE THREAD

**Issue by juliaraz** [visitscotland/vs-component-library#155]
Incorrect colour contrast in Select input on mobile

**Steps to reproduce:**
1. Go to https://feature.visitscotland.com/?vs_brxm_host=172.28.87.25&vs_brxm_port=8027&vs_brxm_http_host=feature.visitscotland.com&vs_ssr_http_port=8227&vs_tln_http_port=8327&vs_feature_branch=PR-30&vs_ssr_proxy=on on mobile
2. Scroll to the PSW
3. Verify the colours

**Actual result:** 
incorrect colour contrast

**Platform:**
IOS and android

![Screenshot 2023-09-07 163226](https://github.com/visitscotland/vs-component-library/assets/131152627/a715ad25-9c05-4fca-996f-010acd62a7df)

![Screenshot 2023-09-08 152754](https://github.com/visitscotland/vs-component-library/assets/131152627/020b2075-2e5b-42c9-9cb6-826ba572f717)

**Comment by MichaelG-PO** [comment]
Another one for you to investigate @duncansanderson

**Comment by duncansanderson** [comment]
There isn't anything that we can do about this as we don't have any control over the styling of the dropdown options, these are styled by the device/browser. There is some limited styling that we can apply but this wouldn't be consistent across different device/browsers.
