### ISSUE TITLE
(Fed) Add missing "in" label to the product search widget

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#188]
### Summary of task
Add missing "in" label to the product search widget in between the "I'm looking for" and "Location"fields as per design. 

https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components-(UI-Kit)?type=design&node-id=1188-9710&mode=design&t=56tkMek84rcEEpVd-0

**Comment by duncansanderson** [comment]
I've update the product search widget to add "in" text as shown on the linked to Figma design.

@CorinaMala you can test this update here: https://646df3398f07e38a95184dbb-gmciaxecsm.chromatic.com/?path=/story/productsearch--default

**Comment by CorinaMala** [comment]
@duncansanderson sorry about the confusion, the desktop view actually matches the ones on figma, I have mistaken the ipad view for the desktop one on the design. **Ready to be merged to develop.**
