### ISSUE TITLE
Add missing "number of nights" display in PSW

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#189]
### Summary of task
The old PSW would show how many nights were selected after a user had selected their date range. This functionality is now missing from the re-factored PSW and should be added back in. 

### Acceptance criteria
Given the product search widget is on the page
And 'Accommodation' or 'Events & Festivals' is selected 
When a start date and end date are both selected
Then the total number of nights should be displayed

Given the start and end dates are both selected
When the Clear button is clicked
Then the dates are cleared 
And the number of nights selected disappears 

### Additional context
Need design input.

**Comment by MichaelGrahamVS** [comment]
Archived due to ASE being removed.
