### ISSUE TITLE
Improve accessibility of guest picker popover in PSW

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#190]
### Summary of task
The guest picker popover can be improved with the following: 
- Loop tabbing so the user stays in the popover until closed
- Close the popover if the user clicks outside of it
- Add the correct ARIA tags for screen readers to announce the popover is open or closed

### Acceptance criteria
TBD

**Comment by MichaelGrahamVS** [comment]
Archiving due to impending removal of ASE.
