### ISSUE TITLE
(FED) Fix vue-warn issues in unit tests

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#211]
### Summary of task
Various vue warnings are appearing in the unit tests. These should be tidied up and fixed where possible. 

### Additional context
![input](https://github.com/visitscotland/vs-component-library/assets/1702460/53f78981-ce95-40df-a3cc-7e03411abf7a)
![pinia](https://github.com/visitscotland/vs-component-library/assets/1702460/fbc177a0-77a0-423d-9a96-7ceaf450d79c)

**Comment by MichaelGrahamVS** [comment]
When @duncansanderson coms to work on this ticket he will run the tests to determine what errors exist and will ask @GemmaLouise for support if required.
