### ISSUE TITLE
(FED) Upgrade Bootstrap 4 to Bootstrap 5

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#263]
Bootstrap 4 code is causing SASS deprecation warnings, remove the dependency to Bootstrap 4 and use Bootstrap 5 styles if needed

Investigate if we can move to Bootstrap 5 and the scope of that

**Comment by GemmaLouise** [comment]
@CorinaMala this can be tested - we have upgraded Bootstrap framework 4 to 5. Have tested as much as I can but will need a bit of a regression test. It would mainly be small UI issues that may be affected but hopefully we have caught most of them. Please note this may affect the third party header so will need tested on the DMS site too - I have a separate PR on that project. Any questions, let me know!

https://feature.visitscotland.com/?vs_brxm_host=172.28.87.25&vs_brxm_port=8001&vs_brxm_http_host=feature.visitscotland.com&vs_ssr_http_port=8201&vs_tln_http_port=8301&vs_feature_branch=PR-454&vs_ssr_proxy=on

**Comment by GemmaLouise** [comment]
@CorinaMala this can be tested - we have upgraded Bootstrap framework 4 to 5. Have tested as much as I can but will need a bit of a regression test. It would mainly be small UI issues that may be affected but hopefully we have caught most of them. Please note this may affect the third party header so will need tested on the DMS site too - I have a separate PR on that project. Any questions, let me know!

https://feature.visitscotland.com/?vs_brxm_host=172.28.87.25&vs_brxm_port=8001&vs_brxm_http_host=feature.visitscotland.com&vs_ssr_http_port=8201&vs_tln_http_port=8301&vs_feature_branch=PR-454&vs_ssr_proxy=on

**Comment by CorinaMala** [comment]
@GemmaLouise the branch you mentioned in the comment has been testing and I couldn't see anything out of ordinary. Would you be able to add the PR branch for the DMS site here or does it have a separate ticket which I can test on?

**Comment by CorinaMala** [comment]
@GemmaLouise as mentioned on the call, the itinerary page is a bit far too zoomed in when accessed https://feature.visitscotland.com/test/pages/itinerary, 
![image](https://github.com/visitscotland/vs-component-library/assets/123950602/e0280056-a3e1-4499-9f84-2525c4a564c7)

**Comment by CorinaMala** [comment]
@GemmaLouise @jlrhurta re-tested after the fix and it looks ok. **Ready to be merged to develop**.
