### ISSUE TITLE
Update Cludo site search with new colour palette

### ISSUE THREAD

**Issue by michaelasemple** [visitscotland/vs-component-library#285]
Along with all components on visitscotland.com visitscotland/vs-component-library#284 , the colours of Cludo site search must also be updated to match.

- [ ] Update style sheet to use the new colour palette

**Comment by kyle-fraser** [comment]
[Link to Pagination figma UI Kit page](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=422%3A1549&mode=design&t=sHy34QEDKlv6xDFo-1)
