### ISSUE TITLE
(FED) Replace search and filter button with hamburger icon

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#307]
### Summary of task
Replace 'OPEN SEARCH & FILTER' button with the term 'MAP MENU' with burger icon and use the secondary style, enabled state design on the map

![Image](https://github.com/visitscotland/vs-component-library/assets/140492229/25f8bd88-ce20-4a42-9921-f7cb7972c807)

### Acceptance criteria
- [ ] Design of hamburger menu has been updated 
- [ ] When clicked, the button opens up the map filters 
- [ ] The hamburger icon is in the secondary style 

### Additional context
Any other information which  may be useful

**Comment by duncansanderson** [comment]
@CorinaMala I've update the map with sidebar component to add the burger menu icon to the map filter button and change the button to the secondary style.

You can test the change here: https://646df3398f07e38a95184dbb-tzmgvbtxdu.chromatic.com/?path=/story/mapwithsidebar--outlander (hopefully this is the correct link that you need for testing)

**Comment by CorinaMala** [comment]
@duncansanderson Tested this on Storybook and can confirm it's looking and working as expected on all maps with a sidebar. Would this be added to the feature env before being merged on dev-nightly?
