### ISSUE TITLE
(FED) Maps - Filter button not opening filter menu

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#309]
### Raised by
Who raised the bug

### Describe the bug
When a user selects the filter button, after they have opened and closed a destination from a pin on the map, the filter menu will not open and instead the pin they had previously selected will display. 

![Image](https://github.com/visitscotland/vs-component-library/assets/140492229/de71e039-4e84-4a9f-8046-2cac267e9813)

### To Reproduce
1. Go to [[(https://www.visitscotland.com/places-to-go)](https://www.visitscotland.com/places-to-go)](https://www.visitscotland.com/places-to-go) on mobile.
2. Click on a map pin and then exit out of it. Click on the filter menu.
3. Previous pin will open up instead of filter menu.

### Expected behavior
Ensure the filter menu displays when the user selects this at any time in their journey.

![Image](https://github.com/visitscotland/vs-component-library/assets/140492229/c876dad3-e338-4217-8cc5-27553fc5944f)

### Page URL
https://www.visitscotland.com/places-to-go 

### Environment
Live 

### Browser
All

### Device and version
If applicable, device the bug was seen on

### Impact on end user
Frustrating user journey

**Comment by MichaelGrahamVS** [comment]
@duncansanderson to catch up with @annacardellini & @aislingwalsh to finalise fix for this issue.

**Comment by duncansanderson** [comment]
Hey @CorinaMala, I've updated the map with sidebar component to fix this issue. This fix also fixes the issue in #310.

You can test the fix here: https://646df3398f07e38a95184dbb-spkicnabqe.chromatic.com/?path=/story/mapwithsidebar--outlander

**Comment by CorinaMala** [comment]
@duncansanderson Ready to be merged to develop
