### ISSUE TITLE
Update components with new tokens: Accordion - ButtonToggleGroup

### ISSUE THREAD

**Issue by michaelasemple** [visitscotland/vs-component-library#312]
Once its been decided how to set up tokens in Figma apply the tokens and update all existing components:

- [x] [Address](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=2884-1385&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] [Accordion](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1188-11809&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] [Alert](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1188-11810&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] Article
    - [x] [ImageWithCaption](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=486-1400&mode=design&t=D4y9DwYAohhGa7S9-0)
    - [x] ToggleButton
    - [x] [Caption](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=486-1400&mode=design&t=73BgRkzlrWTgDePw-0)
    - [x] [Quote](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=2884-3010&mode=design&t=73BgRkzlrWTgDePw-0)
    - [x] [Heading](https://www.figma.com/file/o1uXt3QylTEPxECrwRNXrG/Foundations?type=design&node-id=110-150&mode=design&t=unq983E22jAY2oYs-0)
    - [x] [RichTextWrapper](https://www.figma.com/file/o1uXt3QylTEPxECrwRNXrG/Foundations?type=design&node-id=110-150&mode=design&t=unq983E22jAY2oYs-0)
- [x] [Banner](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=2884-3008&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] [Blog Details](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=2884-3009&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] [Breadcrumb](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1-3&mode=design&t=D4y9DwYAohhGa7S9-0)
- [x] [Button](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=302-2&mode=design&t=73BgRkzlrWTgDePw-0)
- [x] [ButtonToggleGroup](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=2884-3007&mode=design&t=D4y9DwYAohhGa7S9-0)

**Comment by kyle-fraser** [comment]
Hey @GemmaLouise, I've linked all the relevant pages above I've completed so far, I'm working on the actual article pattern/module/component today/tomorrow. 

I also need to add in a ToggleButton still but from the looks of it, the colours used will be _vs-color-background-bold_ and _vs-color-icon-white_.

I'll drop another update on this ticket once I've completed the Article and ToggleButton

**Comment by GemmaLouise** [comment]
I think I've done what I can to this ticket so far, to complete I'm just waiting on: 
- Any Article changes
- ImageWithCaption - design with play button, toggle icons, map location marker colour
- ButtonToggleGroup - button states hover, focus
