### ISSUE TITLE
Update components with new tokens: Carousel - Footer

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#313]
Apply the tokens and update all existing components in Figma and Component Library:

- [x] [Carousel](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1188%3A11807&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Canned Search](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1188%3A11808&mode=design&t=u22c7zoY0MEq3HKU-1)
- [x] [CarbonCalculator](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1188-1008&mode=design&t=EAbF2McxWJ7fc7tX-0)
     - [x] [NumberInput](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=869-2&mode=design&t=EAbF2McxWJ7fc7tX-0)
     - [x] [RadioButton](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=960-863&mode=design&t=EAbF2McxWJ7fc7tX-0)
     - [x] [ProgressBar](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=700-2&mode=design&t=EAbF2McxWJ7fc7tX-0)
- [x] [Checkbox](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3238-3455&mode=design&t=EAbF2McxWJ7fc7tX-0)
- [x] [DescriptionList](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1409%3A3490&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Dropdown](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3583%3A10662&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] EmbedWrapper
- [x] [Footer](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1395-2&mode=design&t=drkBsqO9tWU9PDcT-0)

**Comment by kyle-fraser** [comment]
Hey @GemmaLouise, while i've been finishing off the other ticket (should be completed today), @TessaMinshull has been working through these components. I've updated the checklist with links to the components, there might be slight discprenacies with storybook in terms of states or variants (legacy issues) but the colours you need should all be there. 

Give me a shout if you've any questions.

**Comment by kyle-fraser** [comment]
Hey @GemmaLouise, these should all be up to date now. If anything pops up during implementation just give me a shout
