### ISSUE TITLE
Update components with new tokens: GlobalMenu - MapWithSidebar

### ISSUE THREAD

**Issue by GemmaLouise** [visitscotland/vs-component-library#314]
Apply the tokens and update all existing components in Figma and Component Library:

- [x] [GlobalMenu](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3583%3A10434&mode=design&t=4WW4UVBMf3KQpsO5-1)
- [x] iCentre
    - [x] [Link](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=429%3A1573&mode=design&t=2VKIuRHZxHCLBtCv-1)
- [x] [Icon](https://www.figma.com/file/o1uXt3QylTEPxECrwRNXrG/Foundations?type=design&node-id=310%3A333&mode=design&t=UMELKxN2CUrRsXjo-1)
- [x] [Icon List](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3607%3A3403&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Img](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3623%3A4641&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Input ](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=408%3A3026&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Itinerary](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=1419%3A23&mode=design&t=f67Lo8IMYVxbi1Xp-1)
- [x] [Link List](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=110%3A150&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [List](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3623%3A4692&mode=design&t=acsFEZ68Qupp7SCO-1)
- [x] [Listicle](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3625%3A10027&mode=design&t=f67Lo8IMYVxbi1Xp-1)
- [x] [LoadingSpinner](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=3631%3A10512&mode=design&t=f67Lo8IMYVxbi1Xp-1)
- [x] [Map](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=722%3A47&mode=design&t=0LOM9rhuWXB4blIX-1)
- [x] [MapWithSidebar](https://www.figma.com/file/5Bi3YYUhFHWdgm28gtDtLv/Components?type=design&node-id=722%3A47&mode=design&t=0LOM9rhuWXB4blIX-1)

**Comment by kyle-fraser** [comment]
Hey @GemmaLouise, the figma pages should be up to date with the tokens for this block.

The maps are messy, won't entirely pass accessibility but I can't really avoid that at the moment, the palette is too small either way without repeating myself haha. I'll add a ticket in for the backlog to re-address these issues in future.

Cheers,
Kyle

**Comment by kyle-fraser** [comment]
@GemmaLouise Let me know if this works, I can export at higher quality if needed too

![Image](https://github.com/visitscotland/vs-component-library/assets/140704597/90578f9f-8c42-4a99-99ef-fa4925936f98)
