### ISSUE TITLE
(SE/FED) Investigate Header, Footer, Navigation for savings in weight of pages

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#63]
Following on from ticket [VSD-443](https://jira.visitscotland.com/browse/VSD-443) Create a Page Budget

While researching the make up of weight of pages and modules it was revealed that the weight of an empty page, for example the 404 page, is heavy.

**Goal** 
Want to understand what is making our pages so heavy and what could be done to make them lighter.

**Task**

To investigate where efficiencies can be made on header, footer and navigation and whether any savings in page weight can be achieved.

Key for calculating the carbon footprint of a page is the transfer size of the page.  The number of bytes is then put into a formula to calculate the CO2e g per page load

**Sources**

There is a folder with carbon information here on teams

[Carbon](https://visitscotland.sharepoint.com/:f:/r/sites/VisitScotland.com/Shared%20Documents/General/Carbon?csf=1&web=1&e=cNol1p)

And this website provides analysis of specific pages with data similar to dev tools in an easy read format.

https://www.webpagetest.org/

Original ticket
https://jira.visitscotland.com/browse/VSD-514

**Comment by MichaelGrahamVS** [comment]
Hi @AndyLewis1971 can you remind me how our current approach to caching mitigates this issue? Roughly what percentage of users will this impact?

**Comment by MichaelGrahamVS** [comment]
@jameshaddrillvs is this worth looking into regarding performance improvements and if so would it be FED or SE?

**Comment by jameshaddrillvs** [comment]
@MichaelGrahamVS I think this is probably worth saving for the Business Events performance review as performance may be improved there
